---
# create network
- name: "Create a network"
  docker_network:
    name: "{{ network_name }}"

# run database
- name : "Launch mysql database container"
  docker_container:
    name: "{{ mysql_container }}"
    image: mysql:5.7
    ports:
      - "3306:3306"
    env:
      MYSQL_DATABASE: "{{ mysql_databse }}"
      MYSQL_USER: "{{ mysql_user }}"
      MYSQL_PASSWORD: "{{ mysql_password }}"
      MYSQL_RANDOM_ROOT_PASSWORD: "{{ mysql_root_password }}"
    volumes:
      - "{{ mysql_data }}:/var/lib/mysql"

# run wordpress
- name : "launch wordpress container"
  docker_container:
    name: "{{ wordpress_container }}"
    image: wordpress
    ports:
      - "80:80"
    env:
      WORDPRESS_DB_HOST: mysql_host
      WORDPRESS_DB_USER: "{{ mysql_user }}"
      WORDPRESS_DB_PASSWORD: "{{ mysql_password }}"
      WORDPRESS_DB_NAME: "{{ mysql_databse }}"
    links:
      - "{{ mysql_container }}: mysql_host"
    volumes:
      - "{{ wordpress_data }}:/var/www/html"

# add containers to network
- name: "Add a container to a network"
  docker_network:
    name: "{{ network_name }}"
    connected:
      - "{{ mysql_container }}"
      - "{{ wordpress_container }}"
    appends: yes
